# Generated by Django 4.2.10 on 2024-02-10 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0025_post_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="participate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=100)),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.products"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="cartProduct",),
    ]
