# Generated by Django 4.2.10 on 2024-02-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0026_participate_delete_cartproduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="participate",
            name="e_id",
            field=models.IntegerField(default=12345),
            preserve_default=False,
        ),
    ]
