# Generated by Django 4.2.10 on 2024-02-10 20:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0028_alter_participate_e_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="participate", name="e_id",),
        migrations.AlterField(
            model_name="participate",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
