# Generated by Django 4.2.10 on 2024-02-10 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0029_remove_participate_e_id_alter_participate_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="products", old_name="ratings", new_name="link",
        ),
    ]
