# Generated by Django 4.2.10 on 2024-02-10 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0031_remove_participate_product_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="participate",
            name="description",
            field=models.TextField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="participate",
            name="link",
            field=models.TextField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="participate",
            name="location",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="participate",
            name="name",
            field=models.TextField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="participate",
            name="phone",
            field=models.TextField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="participate",
            name="price",
            field=models.TextField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="participate",
            name="productimg",
            field=models.ImageField(
                default="blank-profile-picture.png", upload_to="productimg"
            ),
        ),
        migrations.AddField(
            model_name="participate",
            name="review",
            field=models.TextField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="participate", name="type", field=models.TextField(blank=True),
        ),
    ]
