# Generated by Django 4.2.10 on 2024-02-11 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0032_participate_description_participate_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participate",
            name="productimg",
            field=models.ImageField(
                default="blank-profile-picture.png", upload_to="participateimg"
            ),
        ),
    ]
